Add safe-local-variable function
PillFall/Emacs-LanguageTool.el pull request #20
Opened 2023-05-23 21:37 UTC by notetiene

* languagetool-core.el: Add `languagetool-local-disabled-rules` safe-local-variable function to check that the variable is a list of strings.

I think that it can be safe to infer that rule IDs must be uppercase and that they may contain underscores.

2023-05-25 02:44 UTC, PillFall requested changes
This would be a great addition.

There is onl one problem, I know the contributing guidelines are still missing, but I only accept the PR if the merge is from develop into develop.

I believe GitHub will mess up with the request if you do it right away, so probably need to recreate or cherry-pick the commit.

2023-05-25 19:13 UTC, notetiene commented
I don't know how to change the head branch of pull requests in GitHub.  Therefore, I reset the fork's master branch to be PillFall:develop.

2023-06-05 21:50 UTC, PillFall approved these changes

2023-06-05 21:57 UTC, PillFall requested changes
Recheck your code, there is an error on byte-compiling.

I believe you didn't `require` `stringp` lib.

2023-06-07 20:53 UTC, notetiene commented
> Recheck your code, there is an error on byte-compiling.
> 
> I believe you didn't `require` `stringp` lib.

My bad.  The  `stringp` is a built-in function and I forgot to include its argument.  I have no idea how it didn't get included in my commit.

It's now fixed.

2023-06-08 01:39 UTC, PillFall approved these changes

2023-06-08 01:39 UTC, merged